export * from "./libraryActions";

export const CONSTANTS = {
    GET_LIBRARY: "GET_LIBRARY",
    PLAY_SONG: "PLAY_SONG",
    PAUSE_SONG: "PAUSE_SONG",
    HANDLE_PLAY: "HANDLE_PLAY",
    HANDLE_PROGRESS: "HANDLE_PROGRESS",
    HANDLE_DURATION: "HANDLE_DURATION",
    HANDLE_SEEK_MOUSEDOWN: "HANDLE_SEEK_MOUSEDOWN",
    HANDLE_SEEK_CHANGE: "HANDLE_SEEK_CHANGE",
    HANDLE_SEEK_MOUSEUP: "HANDLE_SEEK_MOUSEUP",
    HANDLE_VOLUME_CHANGE: "HANDLE_VOLUME_CHANGE",
    HANDLE_TOGGLE_LOOP: "HANDLE_TOGGLE_LOOP",
    HANDLE_TOGGLE_MUTED: "HANDLE_TOGGLE_MUTED"
};